x-deploy: &x-deploy-default
  replicas: ${GRAFANA_LOKI_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.labels.grafana-tempo == true
    preferences:
      - spread: node.labels.grafana-tempo
  labels:
    io.prometheus.enable: "true"
    io.prometheus.scrape_port: "3100"
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging-default
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true
  grafana_tempo:

volumes:
  tempo:

configs:
  tempo.yml:
    file: configs/tempo.yml

services:
  tempo:
    image: grafana/tempo:latest
    command:
      - -target=scalable-single-binary
      - -config.file=/etc/tempo.yml
    networks:
      - dockerswarm_monitoring
      - grafana_tempo
    ports:
      - ${GRAFANA_TEMPO_HTTP_LISTEN_PORT:-3300}:3100 # http_listen_port
    configs:
      - source: tempo.yml
        target: /etc/tempo.yml
    volumes:
      - tempo:/tempo-data
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy: *x-deploy-default
    logging: *x-logging-default
